# Generated by Django 3.0.1 on 2020-04-17 11:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_guestemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default=0, unique=True, upload_to=accounts.models.upload_profile_image),
            preserve_default=False,
        ),
    ]
